// DREAMLOADING - Theme Data Configuration

// Global theme data object
window.themeData = {
    // Space Theme
    space: {
        title: "Space is The Place",
        background: "space",
        elements: [
            { value: "mercury", label: "Mercury" },
            { value: "venus", label: "Venus" },
            { value: "earth", label: "Earth" },
            { value: "mars", label: "Mars" },
            { value: "jupiter", label: "Jupiter" },
            { value: "saturn", label: "Saturn" },
            { value: "uranus", label: "Uranus" },
            { value: "neptune", label: "Neptune" },
            { value: "pluto", label: "Pluto (Dwarf Planet)" },
            { value: "planet", label: "Other Planet" },
            { value: "star", label: "Star" },
            { value: "galaxy", label: "Galaxy" },
            { value: "nebula", label: "Nebula" },
            { value: "black-hole", label: "Black Hole" },
            { value: "asteroid", label: "Asteroid" },
            { value: "asteroid-belt", label: "Asteroid Belt" },
            { value: "comet", label: "Comet" },
            { value: "meteor", label: "Meteor" },
            { value: "moon", label: "Moon" },
            { value: "sun", label: "Sun" },
            { value: "satellite", label: "Satellite" },
            { value: "space-station", label: "Space Station" },
            { value: "rocket", label: "Rocket" },
            { value: "astronaut", label: "Astronaut" },
            { value: "alien", label: "Alien" },
            { value: "ufo", label: "UFO" },
            { value: "telescope", label: "Telescope" },
            { value: "constellation", label: "Constellation" }
        ],
        styles: [
            { value: "cartoon", label: "Cartoon" },
            { value: "realistic", label: "Realistic" },
            { value: "neon", label: "Neon" },
            { value: "pixel-art", label: "Pixel Art" },
            { value: "watercolor", label: "Watercolor" }
        ]
    },
    
    // Underwater Theme
    underwater: {
        title: "Underwater World",
        background: "underwater",
        elements: [
            { value: "fish", label: "Fish" },
            { value: "shark", label: "Shark" },
            { value: "dolphin", label: "Dolphin" },
            { value: "whale", label: "Whale" },
            { value: "octopus", label: "Octopus" },
            { value: "squid", label: "Squid" },
            { value: "jellyfish", label: "Jellyfish" },
            { value: "seahorse", label: "Seahorse" },
            { value: "starfish", label: "Starfish" },
            { value: "coral", label: "Coral" },
            { value: "seaweed", label: "Seaweed" },
            { value: "clam", label: "Clam" },
            { value: "crab", label: "Crab" },
            { value: "lobster", label: "Lobster" },
            { value: "sea-turtle", label: "Sea Turtle" },
            { value: "manta-ray", label: "Manta Ray" },
            { value: "eel", label: "Eel" },
            { value: "sea-urchin", label: "Sea Urchin" },
            { value: "barnacle", label: "Barnacle" },
            { value: "diver", label: "Diver" },
            { value: "submarine", label: "Submarine" },
            { value: "sunken-treasure", label: "Sunken Treasure" },
            { value: "shipwreck", label: "Shipwreck" }
        ],
        styles: [
            { value: "cartoon", label: "Cartoon" },
            { value: "realistic", label: "Realistic" },
            { value: "watercolor", label: "Watercolor" },
            { value: "hand-drawn", label: "Hand Drawn" },
            { value: "pixel-art", label: "Pixel Art" }
        ]
    },
    
    // Animals Theme
    animals: {
        title: "Animal Animals",
        background: "forest",
        elements: [
            { value: "dog", label: "Dog" },
            { value: "cat", label: "Cat" },
            { value: "elephant", label: "Elephant" },
            { value: "lion", label: "Lion" },
            { value: "tiger", label: "Tiger" },
            { value: "giraffe", label: "Giraffe" },
            { value: "zebra", label: "Zebra" },
            { value: "hippo", label: "Hippo" },
            { value: "rhino", label: "Rhino" },
            { value: "monkey", label: "Monkey" },
            { value: "gorilla", label: "Gorilla" },
            { value: "panda", label: "Panda" },
            { value: "koala", label: "Koala" },
            { value: "kangaroo", label: "Kangaroo" },
            { value: "sloth", label: "Sloth" },
            { value: "fox", label: "Fox" },
            { value: "wolf", label: "Wolf" },
            { value: "bear", label: "Bear" },
            { value: "deer", label: "Deer" },
            { value: "moose", label: "Moose" },
            { value: "raccoon", label: "Raccoon" },
            { value: "hedgehog", label: "Hedgehog" },
            { value: "squirrel", label: "Squirrel" },
            { value: "rabbit", label: "Rabbit" },
            { value: "bird", label: "Bird" },
            { value: "owl", label: "Owl" },
            { value: "eagle", label: "Eagle" },
            { value: "penguin", label: "Penguin" },
            { value: "frog", label: "Frog" },
            { value: "turtle", label: "Turtle" },
            { value: "snake", label: "Snake" },
            { value: "lizard", label: "Lizard" },
            { value: "butterfly", label: "Butterfly" },
            { value: "bee", label: "Bee" }
        ],
        styles: [
            { value: "cartoon", label: "Cartoon" },
            { value: "realistic", label: "Realistic" },
            { value: "watercolor", label: "Watercolor" },
            { value: "hand-drawn", label: "Hand Drawn" },
            { value: "origami", label: "Origami" },
            { value: "pixel-art", label: "Pixel Art" }
        ]
    },
    
    // Numbers Theme
    numbers: {
        title: "The Numbers",
        background: "space-numbers",
        elements: [
            { value: "1", label: "One" },
            { value: "2", label: "Two" },
            { value: "3", label: "Three" },
            { value: "4", label: "Four" },
            { value: "5", label: "Five" },
            { value: "6", label: "Six" },
            { value: "7", label: "Seven" },
            { value: "8", label: "Eight" },
            { value: "9", label: "Nine" },
            { value: "10", label: "Ten" },
            { value: "11", label: "Eleven" },
            { value: "12", label: "Twelve" },
            { value: "13", label: "Thirteen" },
            { value: "14", label: "Fourteen" },
            { value: "15", label: "Fifteen" },
            { value: "16", label: "Sixteen" },
            { value: "17", label: "Seventeen" },
            { value: "18", label: "Eighteen" },
            { value: "19", label: "Nineteen" },
            { value: "20", label: "Twenty" },
            { value: "21", label: "Twenty-One" },
            { value: "22", label: "Twenty-Two" },
            { value: "23", label: "Twenty-Three" },
            { value: "24", label: "Twenty-Four" },
            { value: "25", label: "Twenty-Five" },
            { value: "26", label: "Twenty-Six" },
            { value: "27", label: "Twenty-Seven" },
            { value: "28", label: "Twenty-Eight" },
            { value: "29", label: "Twenty-Nine" },
            { value: "30", label: "Thirty" },
            { value: "31", label: "Thirty-One" },
            { value: "32", label: "Thirty-Two" },
            { value: "33", label: "Thirty-Three" },
            { value: "34", label: "Thirty-Four" },
            { value: "35", label: "Thirty-Five" },
            { value: "36", label: "Thirty-Six" },
            { value: "37", label: "Thirty-Seven" },
            { value: "38", label: "Thirty-Eight" },
            { value: "39", label: "Thirty-Nine" },
            { value: "40", label: "Forty" },
            { value: "41", label: "Forty-One" },
            { value: "42", label: "Forty-Two" },
            { value: "43", label: "Forty-Three" },
            { value: "44", label: "Forty-Four" },
            { value: "45", label: "Forty-Five" },
            { value: "46", label: "Forty-Six" },
            { value: "47", label: "Forty-Seven" },
            { value: "48", label: "Forty-Eight" },
            { value: "49", label: "Forty-Nine" },
            { value: "50", label: "Fifty" },
            { value: "51", label: "Fifty-One" },
            { value: "52", label: "Fifty-Two" },
            { value: "53", label: "Fifty-Three" },
            { value: "54", label: "Fifty-Four" },
            { value: "55", label: "Fifty-Five" },
            { value: "56", label: "Fifty-Six" },
            { value: "57", label: "Fifty-Seven" },
            { value: "58", label: "Fifty-Eight" },
            { value: "59", label: "Fifty-Nine" },
            { value: "60", label: "Sixty" },
            { value: "61", label: "Sixty-One" },
            { value: "62", label: "Sixty-Two" },
            { value: "63", label: "Sixty-Three" },
            { value: "64", label: "Sixty-Four" },
            { value: "65", label: "Sixty-Five" },
            { value: "66", label: "Sixty-Six" },
            { value: "67", label: "Sixty-Seven" },
            { value: "68", label: "Sixty-Eight" },
            { value: "69", label: "Sixty-Nine" },
            { value: "70", label: "Seventy" },
            { value: "71", label: "Seventy-One" },
            { value: "72", label: "Seventy-Two" },
            { value: "73", label: "Seventy-Three" },
            { value: "74", label: "Seventy-Four" },
            { value: "75", label: "Seventy-Five" },
            { value: "76", label: "Seventy-Six" },
            { value: "77", label: "Seventy-Seven" },
            { value: "78", label: "Seventy-Eight" },
            { value: "79", label: "Seventy-Nine" },
            { value: "80", label: "Eighty" },
            { value: "81", label: "Eighty-One" },
            { value: "82", label: "Eighty-Two" },
            { value: "83", label: "Eighty-Three" },
            { value: "84", label: "Eighty-Four" },
            { value: "85", label: "Eighty-Five" },
            { value: "86", label: "Eighty-Six" },
            { value: "87", label: "Eighty-Seven" },
            { value: "88", label: "Eighty-Eight" },
            { value: "89", label: "Eighty-Nine" },
            { value: "90", label: "Ninety" },
            { value: "91", label: "Ninety-One" },
            { value: "92", label: "Ninety-Two" },
            { value: "93", label: "Ninety-Three" },
            { value: "94", label: "Ninety-Four" },
            { value: "95", label: "Ninety-Five" },
            { value: "96", label: "Ninety-Six" },
            { value: "97", label: "Ninety-Seven" },
            { value: "98", label: "Ninety-Eight" },
            { value: "99", label: "Ninety-Nine" },
            { value: "100", label: "One Hundred" }
        ],
        styles: [
            { value: "cartoon", label: "Cartoon" },
            { value: "digital", label: "Digital" },
            { value: "3d", label: "3D" },
            { value: "neon", label: "Neon" },
            { value: "pixel-art", label: "Pixel Art" },
            { value: "chalk", label: "Chalk" },
            { value: "colorful", label: "Colorful" }
        ]
    }
};
