name: Remove Background

on:
  repository_dispatch:
    types: [process-image]

jobs:
  remove-background:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install backgroundremover pillow requests

    - name: Download image
      run: |
        python scripts/download_image.py "${{ github.event.client_payload.image_url }}"
        
    - name: Remove background
      run: |
        python scripts/remove_background.py
        
    - name: Commit and push processed image
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add processed_images/
        git commit -m "Add processed image with transparent background" || echo "No changes to commit"
        git push
